apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: quarantine-deny-all
  namespace: microseg-demo
spec:
  endpointSelector:
    matchLabels:
      quarantine: "true"
  ingressDeny:
    - fromEntities:
        - all
  egressDeny:
    - toEntities:
        - all
